# Generated by Django 5.0 on 2023-12-10 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(db_column='RoleID', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
