# Generated by Django 5.0 on 2023-12-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role_id',
            field=models.ForeignKey(db_column='RoleID', default='201edf14-4ad1-446c-9d5a-effde21c2fe6', on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
