# Generated by Django 5.0 on 2023-12-10 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='Type')),
                ('horse_power', models.IntegerField(db_column='HorsePower')),
                ('capacity', models.FloatField(db_column='Capacity')),
                ('torque', models.IntegerField(db_column='Torque')),
                ('fuel_consuption', models.FloatField(db_column='FuelConsuption')),
            ],
            options={
                'db_table': 'Engine',
            },
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='Type')),
                ('gear_number', models.IntegerField(db_column='GearNumber')),
            ],
            options={
                'db_table': 'Gearbox',
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='Type')),
                ('clearance', models.FloatField(db_column='Clearance')),
            ],
            options={
                'db_table': 'Suspension',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(db_column='Mileage')),
                ('body_type', models.CharField(db_column='BodyType')),
                ('year', models.IntegerField(db_column='Year')),
                ('color', models.CharField(db_column='Color')),
                ('vin', models.CharField(db_column='VIN')),
                ('brand', models.ForeignKey(db_column='BrandID', on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
                ('model', models.ForeignKey(db_column='ModelID', on_delete=django.db.models.deletion.CASCADE, to='cars.model')),
                ('engines', models.ManyToManyField(to='cars.engine')),
                ('gearboxes', models.ManyToManyField(to='cars.gearbox')),
                ('suspensions', models.ManyToManyField(to='cars.suspension')),
            ],
            options={
                'db_table': 'Car',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(db_column='Price')),
                ('description', models.CharField(db_column='Description')),
                ('status', models.BooleanField(db_column='Status', default='False')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(db_column='CarID', on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'db_table': 'Ad',
            },
        ),
    ]
