# Generated by Django 5.0 on 2023-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='images',
            field=models.ManyToManyField(to='cars.image'),
        ),
    ]
