# Generated by Django 5.0 on 2023-12-12 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_image_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.IntegerField(db_column='StartPrice')),
                ('start_date', models.DateTimeField(db_column='StartDate')),
                ('end_date', models.DateTimeField(db_column='EndDate')),
                ('description', models.CharField(db_column='Description')),
                ('car', models.ForeignKey(db_column='CarID', on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('images', models.ManyToManyField(to='cars.image')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Auction',
            },
        ),
    ]
