# Generated by Django 5.0 on 2023-12-12 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auction_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.ForeignKey(blank=True, db_column='BidID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.bid'),
        ),
    ]
