# Generated by Django 5.0 on 2023-12-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_auction_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.ForeignKey(blank=True, db_column='BidID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auction_bids', to='cars.bid'),
        ),
    ]
