# Generated by Django 5.0 on 2023-12-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_ad_description_alter_auction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='type',
            field=models.CharField(db_column='Type', max_length=255),
        ),
    ]
