# Generated by Django 5.0 on 2023-12-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='blob',
            field=models.CharField(blank=True, db_column='Blob', null=True),
        ),
    ]
