# Generated by Django 5.0 on 2023-12-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_image_blob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='blob',
        ),
    ]
